name: Build and Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.0'

      - name: Build for Android
        run: flutter build apk

      - name: Build for iOS
        run: flutter build ios --release --no-codesign

      # - name: Build for Web
      #   run: flutter build web

      # - name: Build for Windows
      #   run: flutter build windows

      # - name: Build for macOS
      #   run: flutter build macos

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Compare Commits
        id: compare_commits
        run: echo "::set-output name=commits::$(git log --pretty=format:'- %s' ${{ github.event.before }}...${{ github.event.after }})"

      - name: Publish Release
        id: publish_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release:
            ${{ steps.compare_commits.outputs.commits }}
          draft: false
          prerelease: false

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App-Android
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: App-iOS
          path: build/ios/archive/Runner.ipa

      # - name: Upload Web
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: App-Web
      #     path: build/web

      # - name: Upload EXE
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: App-Windows
      #     path: build/windows/runner/Release

      # - name: Upload DMG
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: App-macOS
      #     path: build/macos/Build/Products/Release/Runner.app
